### PR TITLE
astyle

### PR DESCRIPTION
**Pull request by mreiferson**
```
astyle --style=1tbs --lineend=linux --convert-tabs --preserve-date --pad-header --indent-switches --align-pointer=name --align-reference=name --pad-oper
```

Also removed `typedef`s, I don't like 'em 😀

### CODE REVIEW

**Review by ploxiln — APPROVED** [review]
Looks great. I agree.

You could put the astyle invocation and args into a `style.sh` scriptlet.

**Comment by ploxiln** [comment]
... or just in a "style" `Makefile` target

**Comment by ploxiln** [comment]
I think you accidentally closed without merge?

**Comment by mreiferson** [comment]
Hah, having some fun with `git` this evening.

Seems like I didn't actually have a fork of this repo, and so was actually pushing to `nsqio` and getting very confused.

Anyway, check b5603eab879a07eabd1eaa353c8e578d723e7dfd because I dare not merge a change to the `Makefile` without your 👀

**Comment by ploxiln** [comment]
This Makefile target is more of a "convenience scriptlet" than a "node in the build graph", that's as expected for this, and nice and simple.

Looks great, thanks :)

**Pull request merged**
